export const epiConst = {
  LOAD_EPI_REQUEST: 'LOAD_EPI_REQUEST',
  EPI_FETCHING: 'EPI_FETCHING',
  EPI_FETCHED: 'EPI_FETCHED',
  EPI_FETCHED_FAILED: 'EPI_FETCHED_FAILED',
  EPI_UPDATED: 'EPI_UPDATED',
  EPI_DONE: 'EPI_DONE',
};
